### ISSUE TITLE
Removing backslashes from a string

### ISSUE THREAD

**Issue by eush77** [featurist/shellsubstitute#1]
Hello!

I notice that this module supports escaping, but I find it confusing that a backslash gets removed in the process:

``` js
> substitute('\\${USER}', { USER: 'Josh' })
'${USER}'
```

I would rather expect `'\\${USER}'`.

The reason this is confusing is that it assumes that it's this module's job to interpret escape sequences when in reality it isn't:

``` js
> substitute('\\${USER} \\#{USER} \\\\', { USER: 'Josh' })
'${USER} \\#{USER} \\\\'
```

I would expect either `'\\${USER} \\#{USER} \\\\'` or `'${USER} #{USER} \\'`, not the mix of two.

Another reason to consider leaving backslash in place is that this change would make this module [idempotent](https://en.wikipedia.org/wiki/Idempotence), that is, the result would be the same if the string gets evaluated twice, which is easier to reason about.

**Comment by refractalize** [comment]
hi @eush77,

Problem with `\\$USER` becoming `\\$USER` is that it gives you no way to simply output `$USER`. At least with the backslashes you can do `\\$USER` => `$USER` or `\\\\$USER` => `\\$USER`.

The second part of this is with `#{USER}` which would not interpolate a variable and would normally output `#{USER}` anyway - so naturally there's a difference between the escape handling between `$USER` and `#USER`. Otherwise we'd have to consider all sorts of other symbols when handling escapes (e.g. `% & * @`, etc), which would be crazy.

Does that make sense?

**Comment by eush77** [comment]
> Problem with \$USER becoming \$USER is that it gives you no way to simply output $USER. At least with the backslashes you can do \$USER => $USER or \\$USER => \$USER.

Oh, yeah. It makes sense.

> naturally there's a difference between the escape handling between $USER and #USER

As it is currently implemented, `\\\\\\\\$USER` would collapse to `\\\\$USER`, but `\\\\\\\\#USER` would not change. The downside to that is that it makes the transformation non-regular since It requires now an infinite lookahead (conceptually). It would be simpler in that sense to replace `\\\\` with `\\` regardless of following characters in the input string.
